In [26]:
import mlbgame
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pandas import Series
import datetime
from pandas.tools.plotting import autocorrelation_plot
%matplotlib inline

In [4]:
cd ..

/home/jovyan/dsi

In [15]:
data = pd.read_csv('Capstone/Data/mlb-game-data-1990-2016.csv')

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63862 entries, 0 to 63861
Data columns (total 25 columns):
date               63862 non-null object
box                63862 non-null object
team               63862 non-null object
at                 0 non-null float64
opponent           63862 non-null object
w_or_l             63862 non-null object
runs               63862 non-null int64
runs_allowed       63862 non-null int64
innings            5752 non-null float64
record             63862 non-null object
div_rank           63862 non-null int64
gb                 63862 non-null object
winning_pitcher    63849 non-null object
losing_pitcher     63849 non-null object
save               32469 non-null object
time               63861 non-null object
d_or_n             63861 non-null object
attendance         63380 non-null object
streak             63861 non-null object
double_header      63862 non-null int64
runs_pg            63862 non-null float64
runs_ma            61870 non-null float64
runs_allowed_ma    63862 non-null float64
ten_game           59860 non-null float64
opening_day        63862 non-null int64
dtypes: float64(6), int64(5), object(14)
memory usage: 12.2+ MB

In [17]:
data.drop(['at', 'winning_pitcher', 'losing_pitcher','save','ten_game','box'],axis=1,inplace=True)

In [18]:
data['attendance'].isnull().values.any()

True

In [19]:
print (data[(data["attendance"].isnull()) &  (data["double_header"] == 1)].shape)
print (data[(data["attendance"].isnull()) &  (data["double_header"] == 0)].shape)
print (data[(data["attendance"].notnull()) & (data["double_header"] == 1)].shape)

(478, 19)
(4, 19)
(1048, 19)

In [20]:
nan_dh_df = data[(data["attendance"].isnull()) & (data["double_header"] == 1)].sort_values('date')

In [21]:
for x in list(nan_dh_df.index):
    data['attendance'][x] = data.iloc[x + 1]['attendance']

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [22]:
data[(data["attendance"].isnull()) & (data["double_header"] == 1)].sort_values('date')

Empty DataFrame
Columns: [date, team, opponent, w_or_l, runs, runs_allowed, innings, record, div_rank, gb, time, d_or_n, attendance, streak, double_header, runs_pg, runs_ma, runs_allowed_ma, opening_day]
Index: []

In [27]:
data[(data["attendance"].isnull()) & (data["double_header"] == 0)]

,date,team,opponent,w_or_l,runs,runs_allowed,innings,record,div_rank,gb,time,d_or_n,attendance,streak,double_header,runs_pg,runs_ma,runs_allowed_ma,opening_day
6338,2015-04-29,BAL,CHW,W,8,2,NaN,9-10,4,2.0,2:03,D,NaN,++,0,5.473684,7.2,5.8,0
11256,2015-09-05,CHC,ARI,W,2,0,NaN,76-57,3,9.5,2:34,D,NaN,+,0,4.180451,6.2,5.8,0
19740,1990-05-27,DET,CHW,L,1,2,NaN,20-25,5,4.5,2:55,D,NaN,-,0,4.644444,4.2,4.8,0
37750,1991-06-12,NYM,ATL,L &V;,1,6,NaN,30-25,2,5.5,NaN,NaN,NaN,+,0,4.254545,3.2,2.8,0

In [47]:
data_2015 = pd.read_csv('Capstone/Data/GL2015.TXT',header=None )

In [77]:
data_2015[data_2015[0] == 20150429][17]

304        NaN
305    34220.0
306    10284.0
307    19447.0
308    30055.0
309    16212.0
310    26037.0
311    19633.0
312    12595.0
313    30634.0
314    23012.0
315    53285.0
316    17076.0
317    21824.0
318    40399.0
Name: 17, dtype: float64

In [81]:
data_2015[data_2015[0] == 20150905][17]

2010    39889.0
2011    36534.0
2012    28949.0
2013    27643.0
2014    37827.0
2015    35030.0
2016    27387.0
2017    46373.0
2018        NaN
2019    28632.0
2020    29842.0
2021    37672.0
2022    23135.0
2023    43536.0
2024    45139.0
2025    28646.0
Name: 17, dtype: float64

In [90]:
no_nan_att_data = data[data['attendance'].notnull()]

In [91]:
no_nan_att_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 63858 entries, 0 to 63861
Data columns (total 19 columns):
date               63858 non-null object
team               63858 non-null object
opponent           63858 non-null object
w_or_l             63858 non-null object
runs               63858 non-null int64
runs_allowed       63858 non-null int64
innings            5752 non-null float64
record             63858 non-null object
div_rank           63858 non-null int64
gb                 63858 non-null object
time               63858 non-null object
d_or_n             63858 non-null object
attendance         63858 non-null object
streak             63857 non-null object
double_header      63858 non-null int64
runs_pg            63858 non-null float64
runs_ma            61866 non-null float64
runs_allowed_ma    63858 non-null float64
opening_day        63858 non-null int64
dtypes: float64(4), int64(5), object(10)
memory usage: 9.7+ MB

In [92]:
no_nan_att_data.innings.unique()

array([ nan,  11.,  12.,  13.,  10.,  14.,  17.,  15.,  16.,   7.,   6.,
         8.,   5.,  19.,   9.,  18.,  20.,  22.])

In [93]:
no_nan_att_data['innings'].fillna(9.0,inplace=True)

/opt/conda/lib/python3.6/site-packages/pandas/core/generic.py:3295: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)

In [94]:
no_nan_att_data[no_nan_att_data['streak'].isnull()]

,date,team,opponent,w_or_l,runs,runs_allowed,innings,record,div_rank,gb,time,d_or_n,attendance,streak,double_header,runs_pg,runs_ma,runs_allowed_ma,opening_day
14283,2000-04-04,CIN,MIL,L,1,5,9.0,0-0,2,0.5,3:11,N,"16,761",NaN,0,3.0,NaN,5.4,0

In [104]:
no_nan_att_data.loc[14282]

date               2000-04-03
team                      CIN
opponent                  MIL
w_or_l                      T
runs                        3
runs_allowed                3
innings                     6
record                    0-0
div_rank                    0
gb                          0
time                     1:51
d_or_n                      D
attendance             55,596
streak                      0
double_header               0
runs_pg                     0
runs_ma                   NaN
runs_allowed_ma           5.4
opening_day                 1
Name: 14282, dtype: object

In [105]:
no_nan_att_data['streak'].fillna(0,inplace=True)

/opt/conda/lib/python3.6/site-packages/pandas/core/generic.py:3295: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)

In [106]:
no_nan_att_data["w_or_l"].unique()

array(['L', 'W', 'W-wo', 'T', 'L &H;', 'W &V;', 'W &X;', 'L &V;', 'W &H;'], dtype=object)

In [148]:
no_nan_att_data["w_or_l"].replace(to_replace = ['W-wo','W &V;','W &X;', 'W &H;'], value = ['W','W','W','W'], inplace= True)

/opt/conda/lib/python3.6/site-packages/pandas/core/generic.py:3554: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)

In [150]:
no_nan_att_data["w_or_l"].replace(to_replace = ['L &H;','L &V;'], value =['L','L'], inplace=True)

/opt/conda/lib/python3.6/site-packages/pandas/core/generic.py:3554: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)

In [151]:
no_nan_att_data["w_or_l"].unique()

array(['L', 'W', 'T'], dtype=object)

In [168]:
len(no_nan_att_data.record)

63858

In [153]:
test_rec = no_nan_att_data.record.values

In [161]:
temp_rec_list

[['0', '0'],
 ['0', '1'],
 ['1', '1'],
 ['2', '1'],
 ['2', '2'],
 ['2', '3'],
 ['2', '4'],
 ['3', '4'],
 ['7', '9'],
 ['8', '9'],
 ['8', '10'],
 ['9', '10'],
 ['10', '10'],
 ['10', '11'],
 ['14', '19'],
 ['15', '19'],
 ['16', '19'],
 ['17', '19'],
 ['18', '19'],
 ['19', '19'],
 ['20', '19'],
 ['21', '19'],
 ['21', '20'],
 ['22', '20'],
 ['27', '23'],
 ['27', '24'],
 ['28', '24'],
 ['28', '25'],
 ['28', '26'],
 ['33', '29'],
 ['34', '29'],
 ['34', '30'],
 ['34', '31'],
 ['34', '34'],
 ['35', '34'],
 ['36', '34'],
 ['37', '34'],
 ['42', '39'],
 ['42', '40'],
 ['42', '41'],
 ['42', '42'],
 ['43', '42'],
 ['48', '42'],
 ['49', '42'],
 ['50', '42'],
 ['51', '42'],
 ['52', '42'],
 ['52', '43'],
 ['53', '43'],
 ['60', '47'],
 ['60', '48'],
 ['61', '48'],
 ['62', '48'],
 ['63', '48'],
 ['63', '49'],
 ['64', '49'],
 ['65', '49'],
 ['65', '50'],
 ['66', '50'],
 ['68', '56'],
 ['69', '56'],
 ['69', '57'],
 ['69', '58'],
 ['69', '59'],
 ['70', '59'],
 ['71', '59'],
 ['71', '60'],
 ['72', '60'],
 ['74', '63'],
 ['74', '64'],
 ['75', '70'],
 ['75', '71'],
 ['76', '71'],
 ['76', '72'],
 ['77', '72'],
 ['78', '72'],
 ['78', '73'],
 ['79', '73'],
 ['83', '75'],
 ['83', '76'],
 ['83', '77'],
 ['84', '77'],
 ['0', '0'],
 ['1', '0'],
 ['2', '0'],
 ['2', '1'],
 ['2', '2'],
 ['2', '3'],
 ['3', '3'],
 ['4', '3'],
 ['6', '6'],
 ['6', '7'],
 ['7', '7'],
 ['7', '8'],
 ['7', '9'],
 ['8', '9'],
 ['8', '10'],
 ['15', '11'],
 ['16', '11'],
 ['17', '11'],
 ['17', '12'],
 ['17', '13'],
 ['17', '14'],
 ['17', '15'],
 ['18', '15'],
 ['18', '16'],
 ['21', '21'],
 ['22', '21'],
 ['23', '21'],
 ['24', '21'],
 ['25', '21'],
 ['25', '22'],
 ['25', '23'],
 ['25', '24'],
 ['31', '26'],
 ['32', '26'],
 ['33', '26'],
 ['39', '28'],
 ['40', '28'],
 ['41', '28'],
 ['42', '28'],
 ['42', '29'],
 ['43', '29'],
 ['44', '29'],
 ['45', '29'],
 ['48', '32'],
 ['49', '32'],
 ['49', '33'],
 ['49', '34'],
 ['49', '35'],
 ['49', '36'],
 ['51', '41'],
 ['52', '41'],
 ['52', '42'],
 ['52', '43'],
 ['53', '43'],
 ['57', '47'],
 ['57', '48'],
 ['58', '48'],
 ['58', '49'],
 ['58', '50'],
 ['58', '51'],
 ['58', '52'],
 ['59', '52'],
 ['60', '52'],
 ['66', '57'],
 ['67', '57'],
 ['67', '58'],
 ['68', '58'],
 ['69', '58'],
 ['69', '59'],
 ['70', '59'],
 ['77', '63'],
 ['77', '64'],
 ['78', '64'],
 ['79', '64'],
 ['79', '65'],
 ['81', '71'],
 ['81', '72'],
 ['82', '72'],
 ['83', '72'],
 ['83', '73'],
 ['83', '74'],
 ['0', '0'],
 ['1', '0'],
 ['1', '1'],
 ['5', '5'],
 ['6', '5'],
 ['6', '6'],
 ['7', '11'],
 ['8', '11'],
 ['8', '12'],
 ['9', '12'],
 ['10', '12'],
 ['11', '12'],
 ['11', '13'],
 ['12', '13'],
 ['16', '19'],
 ['17', '19'],
 ['17', '20'],
 ['21', '23'],
 ['22', '23'],
 ['22', '24'],
 ['22', '25'],
 ['22', '26'],
 ['23', '26'],
 ['24', '26'],
 ['24', '27'],
 ['25', '27'],
 ['28', '31'],
 ['28', '32'],
 ['29', '32'],
 ['32', '39'],
 ['33', '39'],
 ['34', '39'],
 ['35', '39'],
 ['35', '40'],
 ['35', '41'],
 ['37', '43'],
 ['37', '44'],
 ['38', '44'],
 ['41', '45'],
 ['42', '45'],
 ['42', '46'],
 ['42', '47'],
 ['42', '48'],
 ['42', '49'],
 ['43', '57'],
 ['43', '58'],
 ['43', '59'],
 ['44', '59'],
 ['44', '60'],
 ['44', '61'],
 ['45', '61'],
 ['46', '61'],
 ['46', '62'],
 ['46', '63'],
 ['46', '64'],
 ['46', '65'],
 ['46', '66'],
 ['49', '71'],
 ['50', '71'],
 ['50', '72'],
 ['50', '73'],
 ['51', '73'],
 ['51', '74'],
 ['51', '82'],
 ['52', '82'],
 ['52', '83'],
 ['52', '84'],
 ['53', '84'],
 ['54', '84'],
 ['61', '86'],
 ['61', '87'],
 ['61', '88'],
 ['61', '89'],
 ['62', '89'],
 ['63', '89'],
 ['65', '91'],
 ['65', '92'],
 ['66', '92'],
 ['67', '92'],
 ['68', '92'],
 ['69', '92'],
 ['0', '0'],
 ['0', '1'],
 ['0', '2'],
 ['1', '2'],
 ['2', '2'],
 ['3', '2'],
 ['3', '3'],
 ['4', '3'],
 ['5', '3'],
 ['9', '10'],
 ['10', '10'],
 ['10', '11'],
 ['11', '11'],
 ['11', '12'],
 ['11', '13'],
 ['12', '13'],
 ['16', '16'],
 ['17', '16'],
 ['17', '17'],
 ['17', '18'],
 ['18', '18'],
 ['18', '19'],
 ['18', '20'],
 ['19', '20'],
 ['19', '21'],
 ['20', '21'],
 ['21', '21'],
 ['22', '21'],
 ['27', '26'],
 ['28', '26'],
 ['28', '27'],
 ['29', '27'],
 ['29', '28'],
 ['30', '28'],
 ['35', '33'],
 ['35', '34'],
 ['36', '34'],
 ['37', '34'],
 ['38', '34'],
 ['38', '35'],
 ['39', '35'],
 ['40', '38'],
 ['41', '38'],
 ['42', '38'],
 ['42', '39'],
 ['42', '40'],
 ['43', '40'],
 ['43', '41'],
 ['44', '41'],
 ['45', '41'],
 ['46', '41'],
 ['51', '43'],
 ['51', '44'],
 ['54', '48'],
 ['54', '49'],
 ['55', '49'],
 ['56', '49'],
 ['56', '50'],
 ['57', '50'],
 ['57', '51'],
 ['57', '55'],
 ['58', '55'],
 ['59', '55'],
 ['59', '56'],
 ['60', '56'],
 ['61', '56'],
 ['65', '62'],
 ['66', '62'],
 ['66', '63'],
 ['67', '63'],
 ['67', '64'],
 ['68', '64'],
 ['70', '70'],
 ['71', '70'],
 ['71', '71'],
 ['72', '71'],
 ['72', '72'],
 ['73', '72'],
 ['81', '78'],
 ['82', '78'],
 ['82', '79'],
 ['3', '3'],
 ['3', '4'],
 ['4', '4'],
 ['5', '4'],
 ['6', '4'],
 ['6', '5'],
 ['6', '6'],
 ['6', '7'],
 ['6', '8'],
 ['10', '15'],
 ['11', '15'],
 ['12', '15'],
 ['13', '15'],
 ['14', '15'],
 ['14', '16'],
 ['17', '20'],
 ['17', '21'],
 ['18', '21'],
 ['19', '21'],
 ['19', '22'],
 ['19', '23'],
 ['23', '26'],
 ['23', '27'],
 ['23', '28'],
 ['24', '28'],
 ['25', '28'],
 ['26', '28'],
 ['27', '28'],
 ['28', '28'],
 ['28', '29'],
 ['31', '33'],
 ['31', '34'],
 ['32', '34'],
 ['36', '37'],
 ['37', '37'],
 ['37', '38'],
 ['38', '38'],
 ['38', '39'],
 ['38', '40'],
 ['38', '41'],
 ['42', '45'],
 ['43', '45'],
 ['43', '46'],
 ['43', '47'],
 ['43', '48'],
 ['44', '48'],
 ['50', '49'],
 ['51', '49'],
 ['51', '50'],
 ['52', '50'],
 ['52', '51'],
 ['53', '51'],
 ['58', '54'],
 ['59', '54'],
 ['59', '55'],
 ['60', '55'],
 ['61', '55'],
 ['61', '56'],
 ['66', '58'],
 ['66', '59'],
 ['66', '60'],
 ['67', '60'],
 ['67', '61'],
 ['68', '61'],
 ['68', '62'],
 ['70', '67'],
 ['70', '68'],
 ['71', '68'],
 ['72', '68'],
 ['73', '68'],
 ['73', '69'],
 ['73', '70'],
 ['74', '79'],
 ['74', '80'],
 ['75', '80'],
 ['75', '81'],
 ['75', '82'],
 ['75', '83'],
 ['75', '84'],
 ['75', '85'],
 ['75', '86'],
 ['0', '0'],
 ['0', '1'],
 ['1', '1'],
 ['3', '2'],
 ['3', '3'],
 ['3', '4'],
 ['3', '5'],
 ['3', '6'],
 ['3', '7'],
 ['3', '8'],
 ['4', '8'],
 ['5', '8'],
 ['7', '14'],
 ['8', '14'],
 ['9', '14'],
 ['15', '15'],
 ['15', '16'],
 ['16', '16'],
 ['17', '16'],
 ['18', '16'],
 ['19', '16'],
 ['24', '17'],
 ['25', '17'],
 ['26', '17'],
 ['27', '17'],
 ['27', '18'],
 ['28', '18'],
 ['31', '22'],
 ['32', '22'],
 ['33', '22'],
 ['34', '22'],
 ['34', '23'],
 ['35', '23'],
 ['35', '24'],
 ['36', '24'],
 ['37', '24'],
 ['37', '25'],
 ['45', '32'],
 ['45', '33'],
 ['46', '33'],
 ['47', '33'],
 ['47', '34'],
 ['48', '34'],
 ['48', '35'],
 ['49', '35'],
 ['50', '35'],
 ['55', '39'],
 ['56', '39'],
 ['57', '39'],
 ['58', '39'],
 ['58', '40'],
 ['59', '40'],
 ['62', '41'],
 ['63', '41'],
 ['63', '42'],
 ['63', '43'],
 ['64', '43'],
 ['64', '44'],
 ['65', '44'],
 ['69', '48'],
 ['70', '48'],
 ['71', '48'],
 ['72', '48'],
 ['73', '48'],
 ['73', '49'],
 ['77', '53'],
 ['78', '53'],
 ['78', '54'],
 ['79', '54'],
 ['80', '54'],
 ['81', '54'],
 ['88', '54'],
 ['88', '55'],
 ['89', '55'],
 ['90', '55'],
 ['91', '55'],
 ['92', '55'],
 ['93', '55'],
 ['97', '62'],
 ['97', '63'],
 ['98', '63'],
 ['0', '0'],
 ['0', '1'],
 ['1', '1'],
 ['4', '5'],
 ['5', '5'],
 ['6', '5'],
 ['8', '8'],
 ['8', '9'],
 ['9', '9'],
 ['9', '10'],
 ['9', '11'],
 ['9', '12'],
 ['10', '12'],
 ['10', '13'],
 ['11', '13'],
 ['13', '17'],
 ['14', '17'],
 ['15', '17'],
 ['16', '17'],
 ['17', '17'],
 ['17', '18'],
 ['21', '21'],
 ['22', '21'],
 ['22', '22'],
 ['22', '23'],
 ['22', '24'],
 ['23', '24'],
 ['31', '29'],
 ['31', '30'],
 ['32', '30'],
 ['33', '30'],
 ['33', '31'],
 ['34', '31'],
 ['36', '37'],
 ['36', '38'],
 ['37', '38'],
 ['37', '39'],
 ['38', '39'],
 ['39', '39'],
 ['40', '39'],
 ['40', '40'],
 ['41', '40'],
 ['42', '40'],
 ['44', '42'],
 ['44', '43'],
 ['45', '43'],
 ['46', '43'],
 ['47', '43'],
 ['48', '43'],
 ['51', '49'],
 ['51', '50'],
 ['51', '51'],
 ['51', '52'],
 ['52', '52'],
 ['52', '53'],
 ['52', '54'],
 ['52', '55'],
 ['53', '55'],
 ['53', '56'],
 ['54', '63'],
 ['55', '63'],
 ['55', '64'],
 ['56', '64'],
 ['57', '64'],
 ['58', '64'],
 ['59', '64'],
 ['63', '68'],
 ['63', '69'],
 ['64', '69'],
 ['67', '72'],
 ['67', '73'],
 ['68', '73'],
 ['69', '73'],
 ['71', '79'],
 ['71', '80'],
 ['72', '80'],
 ['73', '83'],
 ['73', '84'],
 ['74', '84'],
 ['75', '84'],
 ['76', '84'],
 ['76', '85'],
 ['4', '3'],
 ['5', '3'],
 ['6', '3'],
 ['6', '4'],
 ['6', '5'],
 ['7', '5'],
 ['7', '6'],
 ['7', '7'],
 ['7', '8'],
 ['15', '10'],
 ['16', '10'],
 ['17', '10'],
 ['18', '10'],
 ['19', '10'],
 ['20', '10'],
 ['21', '10'],
 ['25', '13'],
 ['26', '13'],
 ['26', '14'],
 ['26', '15'],
 ['27', '15'],
 ['28', '15'],
 ['30', '20'],
 ['31', '20'],
 ['32', '20'],
 ['33', '20'],
 ['33', '21'],
 ['33', '22'],
 ['33', '23'],
 ['33', '24'],
 ['33', '25'],
 ['34', '25'],
 ['35', '25'],
 ['35', '26'],
 ['37', '31'],
 ['38', '31'],
 ['39', '31'],
 ['39', '32'],
 ['41', '37'],
 ['42', '37'],
 ['42', '38'],
 ['47', '40'],
 ['48', '40'],
 ['48', '41'],
 ['49', '41'],
 ['49', '42'],
 ['49', '43'],
 ['52', '46'],
 ['52', '47'],
 ['53', '47'],
 ['54', '47'],
 ['54', '48'],
 ['55', '48'],
 ['56', '48'],
 ['62', '50'],
 ['62', '51'],
 ['63', '51'],
 ['63', '52'],
 ['63', '53'],
 ['64', '53'],
 ['70', '54'],
 ['71', '54'],
 ['72', '54'],
 ['73', '54'],
 ['74', '54'],
 ['74', '55'],
 ['78', '58'],
 ['79', '58'],
 ['79', '59'],
 ['79', '60'],
 ['80', '60'],
 ['80', '61'],
 ['83', '63'],
 ['84', '63'],
 ['84', '64'],
 ['84', '65'],
 ['85', '65'],
 ['85', '66'],
 ['85', '67'],
 ['85', '68'],
 ['86', '68'],
 ['0', '0'],
 ['0', '1'],
 ['0', '2'],
 ['0', '3'],
 ['0', '4'],
 ['0', '5'],
 ['3', '13'],
 ['4', '13'],
 ['5', '13'],
 ['5', '14'],
 ['7', '18'],
 ['7', '19'],
 ['8', '28'],
 ['8', '29'],
 ['8', '30'],
 ['8', '31'],
 ['9', '31'],
 ['10', '31'],
 ['10', '32'],
 ['11', '32'],
 ['14', '32'],
 ['14', '33'],
 ['14', '34'],
 ['15', '34'],
 ['16', '34'],
 ['16', '35'],
 ['20', '43'],
 ['20', '44'],
 ['21', '44'],
 ['21', '45'],
 ['21', '46'],
 ['22', '46'],
 ['26', '51'],
 ['26', '52'],
 ['26', '53'],
 ['27', '53'],
 ['27', '54'],
 ['30', '58'],
 ['30', '59'],
 ['30', '60'],
 ['30', '61'],
 ['31', '61'],
 ['31', '62'],
 ['32', '62'],
 ['33', '62'],
 ['34', '62'],
 ['37', '67'],
 ['37', '68'],
 ['38', '68'],
 ['38', '69'],
 ['44', '73'],
 ['44', '74'],
 ['45', '74'],
 ['45', '75'],
 ['45', '76'],
 ['45', '77'],
 ['46', '77'],
 ['47', '77'],
 ['47', '78'],
 ['50', '82'],
 ['50', '83'],
 ['50', '84'],
 ['50', '85'],
 ['51', '85'],
 ['52', '85'],
 ['56', '85'],
 ['57', '85'],
 ['57', '86'],
 ['57', '87'],
 ['58', '87'],
 ['58', '88'],
 ['59', '91'],
 ['60', '91'],
 ['61', '91'],
 ['61', '92'],
 ['61', '93'],
 ['62', '93'],
 ['62', '94'],
 ['63', '96'],
 ['64', '96'],
 ['65', '96'],
 ['1', '5'],
 ['2', '5'],
 ['3', '5'],
 ['4', '5'],
 ['4', '6'],
 ['5', '6'],
 ['5', '7'],
 ['6', '7'],
 ['7', '7'],
 ['8', '7'],
 ['15', '14'],
 ['16', '14'],
 ['16', '15'],
 ['17', '15'],
 ['18', '15'],
 ['19', '15'],
 ['20', '15'],
 ['20', '16'],
 ['21', '16'],
 ['24', '21'],
 ['25', '21'],
 ['26', '21'],
 ['32', '22'],
 ['33', '22'],
 ['33', '23'],
 ['34', '23'],
 ['34', '24'],
 ['34', '25'],
 ['37', '26'],
 ['38', '26'],
 ['39', '26'],
 ['40', '26'],
 ['40', '27'],
 ['41', '27'],
 ['41', '28'],
 ['41', '29'],
 ['41', '30'],
 ['41', '31'],
 ['42', '31'],
 ['42', '32'],
 ['42', '33'],
 ['45', '38'],
 ['45', '39'],
 ['46', '39'],
 ['47', '39'],
 ['47', '40'],
 ['47', '41'],
 ['52', '45'],
 ['53', '45'],
 ['54', '45'],
 ['59', '47'],
 ['60', '47'],
 ['60', '48'],
 ['66', '49'],
 ['66', '50'],
 ['66', '51'],
 ['67', '51'],
 ['68', '51'],
 ['69', '51'],
 ['76', '52'],
 ['76', '53'],
 ['77', '53'],
 ['78', '53'],
 ['79', '53'],
 ['79', '54'],
 ['83', '57'],
 ['84', '57'],
 ['85', '57'],
 ['86', '57'],
 ['87', '57'],
 ['88', '57'],
 ['88', '58'],
 ['88', '59'],
 ['89', '59'],
 ['95', '60'],
 ['96', '60'],
 ['97', '60'],
 ['97', '61'],
 ['98', '61'],
 ['98', '62'],
 ['99', '62'],
 ['0', '0'],
 ['1', '0'],
 ['2', '0'],
 ['3', '0'],
 ['3', '1'],
 ['4', '1'],
 ['9', '3'],
 ['9', '4'],
 ['10', '4'],
 ['11', '4'],
 ['12', '4'],
 ['12', '5'],
 ['12', '6'],
 ['18', '10'],
 ['19', '10'],
 ['20', '10'],
 ['21', '10'],
 ['22', '10'],
 ['23', '10'],
 ['27', '16'],
 ['28', '16'],
 ['29', '16'],
 ['30', '16'],
 ['31', '16'],
 ['32', '16'],
 ['32', '17'],
 ['32', '18'],
 ['32', '19'],
 ['33', '19'],
 ['35', '24'],
 ['36', '24'],
 ['36', '25'],
 ['39', '29'],
 ['40', '29'],
 ['40', '30'],
 ['41', '30'],
 ['42', '30'],
 ['42', '31'],
 ['43', '31'],
 ['44', '31'],
 ['44', '32'],
 ['45', '32'],
 ['46', '32'],
 ['46', '33'],
 ['47', '33'],
 ['47', '34'],
 ['51', '37'],
 ['51', '38'],
 ['52', '38'],
 ['52', '39'],
 ['52', '40'],
 ['53', '40'],
 ['53', '41'],
 ['54', '41'],
 ['58', '47'],
 ['58', '48'],
 ['59', '48'],
 ['60', '48'],
 ['60', '49'],
 ['60', '50'],
 ['61', '50'],
 ['62', '50'],
 ['62', '51'],
 ['67', '53'],
 ['68', '53'],
 ['69', '53'],
 ['70', '53'],
 ['70', '54'],
 ['70', '55'],
 ['73', '59'],
 ['73', '60'],
 ['73', '61'],
 ['76', '65'],
 ['76', '66'],
 ['77', '66'],
 ['78', '66'],
 ['79', '66'],
 ['79', '67'],
 ['84', '75'],
 ['84', '76'],
 ['85', '76'],
 ['2', '1'],
 ['2', '2'],
 ['2', '3'],
 ['2', '4'],
 ['3', '4'],
 ['3', '5'],
 ['6', '9'],
 ['7', '9'],
 ['8', '9'],
 ['8', '10'],
 ['9', '10'],
 ['10', '10'],
 ['11', '10'],
 ['12', '10'],
 ['12', '11'],
 ['12', '12'],
 ['16', '15'],
 ['16', '16'],
 ['17', '16'],
 ['18', '16'],
 ['18', '17'],
 ['18', '18'],
 ['23', '20'],
 ['24', '20'],
 ['25', '20'],
 ['31', '22'],
 ['32', '22'],
 ['33', '22'],
 ['34', '22'],
 ['34', '23'],
 ['34', '24'],
 ['35', '24'],
 ['38', '25'],
 ['38', '26'],
 ['39', '26'],
 ['40', '26'],
 ['40', '27'],
 ['41', '27'],
 ['46', '29'],
 ['46', '30'],
 ['46', '31'],
 ['47', '31'],
 ['48', '31'],
 ['49', '31'],
 ['51', '33'],
 ['51', '34'],
 ['51', '35'],
 ['57', '41'],
 ['57', '42'],
 ['58', '42'],
 ['59', '42'],
 ['59', '43'],
 ['59', '44'],
 ['59', '45'],
 ['59', '46'],
 ['60', '46'],
 ['60', '47'],
 ['60', '48'],
 ['61', '48'],
 ['61', '49'],
 ['66', '51'],
 ['67', '51'],
 ['68', '51'],
 ['69', '51'],
 ['70', '51'],
 ['71', '51'],
 ['75', '55'],
 ['76', '55'],
 ['77', '55'],
 ['79', '61'],
 ['79', '62'],
 ['80', '62'],
 ['84', '66'],
 ['84', '67'],
 ['85', '67'],
 ['86', '67'],
 ['87', '67'],
 ['88', '67'],
 ['88', '68'],
 ['89', '68'],
 ['90', '68'],
 ['0', '0'],
 ['1', '0'],
 ['2', '0'],
 ['8', '5'],
 ['9', '5'],
 ['10', '5'],
 ['10', '6'],
 ['10', '7'],
 ['11', '7'],
 ['16', '9'],
 ['16', '10'],
 ['16', '11'],
 ['17', '11'],
 ['18', '11'],
 ['19', '11'],
 ['20', '11'],
 ['20', '12'],
 ['21', '12'],
 ['25', '15'],
 ['26', '15'],
 ['27', '15'],
 ['28', '15'],
 ['28', '16'],
 ['29', '16'],
 ['29', '17'],
 ['30', '17'],
 ...]

In [160]:
temp_rec_list = []
for x in test_rec:
    temp_rec_list.append( x.split("-"))

In [163]:
w_percent = []
for x, y in temp_rec_list:
    if (int(x) + int (y)) != 0:
        w_percent.append(int(x)/(int(x) + int (y)))
    if (int(x) + int (y)) == 0:
        w_percent.append(0)

In [169]:
no_nan_att_data.record = w_percent

/opt/conda/lib/python3.6/site-packages/pandas/core/generic.py:2773: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value

In [218]:
test_gb= no_nan_att_data.copy()
test_gb

,date,team,opponent,w_or_l,runs,runs_allowed,innings,record,div_rank,gb,time,d_or_n,attendance,streak,double_header,runs_pg,runs_ma,runs_allowed_ma,opening_day
0,1997-04-02,ANA,BOS,L,5,6,9.0,0.000000,0,0,3:47,N,"30,874",0,0,0.000000,NaN,5.8,1
1,1997-04-03,ANA,BOS,W,2,0,9.0,0.000000,3,1.0,2:07,N,"17,323",-,0,5.000000,NaN,5.8,0
2,1997-04-04,ANA,CLE,W,8,6,11.0,0.500000,2,0.5,4:12,N,"17,758",+,0,3.500000,NaN,5.8,0
3,1997-04-05,ANA,CLE,L,5,7,9.0,0.666667,1,Tied,3:09,N,"23,913",++,0,5.000000,NaN,5.8,0
4,1997-04-06,ANA,CLE,L,8,10,9.0,0.500000,1,Tied,3:24,N,"29,363",-,0,5.000000,NaN,5.8,0
5,1997-04-07,ANA,NYY,L,3,5,9.0,0.400000,3,1.0,3:24,N,"16,514",--,0,5.600000,5.6,5.8,0
6,1997-04-08,ANA,NYY,W,10,9,12.0,0.333333,3,2.0,4:18,N,"17,202",---,0,5.166667,5.2,5.6,0
7,1997-04-09,ANA,NYY,L,5,12,9.0,0.428571,2,1.0,2:52,N,"19,242",+,0,5.857143,6.8,7.4,0
8,1997-04-21,ANA,TOR,W,5,4,13.0,0.437500,4,3.0,4:04,N,"13,413",+,0,5.437500,5.0,4.2,0
9,1997-04-22,ANA,TOR,L,6,7,9.0,0.470588,4,3.0,2:44,N,"13,353",++,0,5.411765,4.8,4.0,0
10,1997-04-23,ANA,TOR,W,5,4,10.0,0.444444,4,4.0,3:13,N,"13,117",-,0,5.444444,5.6,4.6,0
11,1997-04-25,ANA,DET,W,8,3,9.0,0.473684,4,3.0,2:49,N,"30,464",+,0,5.421053,6.0,4.6,0
12,1997-04-26,ANA,DET,L,0,2,9.0,0.500000,3,3.0,2:18,N,"30,872",++,0,5.550000,7.0,3.8,0
13,1997-04-27,ANA,DET,W,6,5,9.0,0.476190,4,3.0,3:06,D,"16,409",-,0,5.285714,4.8,4.0,0
14,1997-05-12,ANA,CHW,W,16,8,9.0,0.424242,3,6.0,3:44,N,"14,540",-----,0,4.575758,2.6,5.0,0
15,1997-05-13,ANA,CHW,W,8,7,9.0,0.441176,3,5.0,3:18,N,"14,806",+,0,4.911765,5.0,5.0,0
16,1997-05-14,ANA,BAL,W,6,5,9.0,0.457143,3,5.0,2:55,N,"15,780",++,0,5.000000,6.6,5.8,0
17,1997-05-15,ANA,BAL,W,3,2,9.0,0.472222,3,5.0,2:58,N,"15,966",+++,0,5.027778,7.0,5.8,0
18,1997-05-16,ANA,MIL,W,5,1,9.0,0.486486,3,4.0,2:46,N,"26,033",++++,0,4.972973,7.0,5.4,0
19,1997-05-17,ANA,MIL,W,6,5,9.0,0.500000,3,3.0,3:12,N,"34,922",+++++,0,4.973684,7.6,4.6,0
20,1997-05-18,ANA,MIL,W,5,4,9.0,0.512821,3,2.0,2:26,D,"16,665",++++++,0,5.000000,5.6,4.0,0
21,1997-05-19,ANA,SEA,L,4,13,9.0,0.525000,3,2.0,3:08,N,"17,279",+++++++,0,5.000000,5.0,3.4,0
22,1997-05-20,ANA,SEA,W,11,9,9.0,0.512195,3,2.5,3:27,N,"17,492",-,0,4.975610,4.6,5.0,0
23,1997-05-21,ANA,SEA,W,18,3,9.0,0.523810,3,2.5,3:18,N,"20,295",+,0,5.119048,6.2,6.4,0
24,1997-05-30,ANA,MIN,L,3,4,9.0,0.540000,2,1.0,2:49,N,"28,922",++,0,5.480000,5.2,5.4,0
25,1997-05-31,ANA,MIN,W,5,3,9.0,0.529412,2,1.0,2:57,N,"19,147",-,0,5.431373,5.2,5.4,0
26,1997-06-01,ANA,MIN,L,4,5,9.0,0.538462,2,1.0,3:52,D,"23,875",+,0,5.423077,6.2,4.8,0
27,1997-06-03,ANA,KCR,L,2,5,9.0,0.528302,2,1.0,2:36,N,"14,492",-,0,5.396226,6.6,4.6,0
28,1997-06-04,ANA,KCR,W,7,3,9.0,0.518519,3,1.5,2:39,N,"13,220",--,0,5.333333,4.2,3.6,0
29,1997-06-12,ANA,SDP,W,8,4,9.0,0.532258,2,0.5,3:11,N,"22,164",-,0,5.370968,5.6,5.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63832,2016-08-05,WSN,SFG,W,5,1,9.0,0.592593,1,up 7.0,2:26,N,"34,036",+++,0,4.768519,7.2,3.2,0
63833,2016-08-06,WSN,SFG,L,1,7,9.0,0.596330,1,up 7.0,3:29,N,"36,404",++++,0,4.770642,7.6,2.4,0
63834,2016-08-07,WSN,SFG,W,1,0,9.0,0.590909,1,up 7.0,2:43,D,"32,790",-,0,4.736364,7.6,3.2,0
63835,2016-08-09,WSN,CLE,L,1,3,9.0,0.594595,1,up 7.0,2:55,N,"30,978",+,0,4.702703,5.0,3.0,0
63836,2016-08-10,WSN,CLE,W,7,4,9.0,0.589286,1,up 6.5,2:52,D,"30,185",-,0,4.669643,3.2,2.8,0
63837,2016-08-12,WSN,ATL,L,5,8,9.0,0.592920,1,up 7.5,3:15,N,"29,089",+,0,4.690265,3.0,3.0,0
63838,2016-08-13,WSN,ATL,W,7,6,9.0,0.587719,1,up 7.5,3:07,N,"38,490",-,0,4.692982,3.0,4.4,0
63839,2016-08-14,WSN,ATL,W,9,1,9.0,0.591304,1,up 8.5,2:46,D,"29,107",+,0,4.713043,4.2,4.2,0
63840,2016-08-24,WSN,BAL,L,8,10,9.0,0.584000,1,up 8.0,3:28,N,"39,100",---,0,4.832000,5.6,6.8,0
63841,2016-08-25,WSN,BAL,W,4,0,9.0,0.579365,1,up 7.0,2:43,N,"39,722",----,0,4.857143,5.8,7.6,0
63842,2016-08-26,WSN,COL,W,8,5,9.0,0.582677,1,up 8.0,3:04,N,"33,433",+,0,4.850394,4.4,5.8,0
63843,2016-08-27,WSN,COL,L,4,9,11.0,0.585938,1,up 8.0,4:49,D,"27,901",++,0,4.875000,4.8,5.4,0
63844,2016-08-28,WSN,COL,L,3,5,9.0,0.581395,1,up 8.0,2:52,D,"28,124",-,0,4.868217,5.0,6.4,0
63845,2016-09-05,WSN,ATL,W,6,4,9.0,0.580882,1,up 8.5,2:59,D,"26,005",--,0,4.750000,2.2,2.4,0
63846,2016-09-06,WSN,ATL,W,9,7,9.0,0.583942,1,up 8.5,3:38,N,"17,161",+,0,4.759124,2.8,2.8,0
63847,2016-09-07,WSN,ATL,W,5,4,11.0,0.586957,1,up 8.5,4:39,N,"19,894",++,0,4.789855,4.2,4.0,0
63848,2016-09-08,WSN,PHI,L,1,4,9.0,0.589928,1,up 8.5,2:48,N,"25,412",+++,0,4.791367,4.4,4.6,0
63849,2016-09-09,WSN,PHI,W,5,4,9.0,0.585714,1,up 8.0,3:31,N,"28,469",-,0,4.764286,4.4,4.8,0
63850,2016-09-10,WSN,PHI,W,3,0,9.0,0.588652,1,up 8.0,3:05,N,"36,152",+,0,4.765957,5.2,4.6,0
63851,2016-09-11,WSN,PHI,W,3,2,9.0,0.591549,1,up 9.0,2:49,D,"31,805",++,0,4.753521,4.6,3.8,0
63852,2016-09-12,WSN,NYM,W,8,1,9.0,0.594406,1,up 9.0,3:08,N,"22,832",+++,0,4.741259,3.4,2.8,0
63853,2016-09-13,WSN,NYM,L,3,4,10.0,0.597222,1,up10.0,3:22,N,"25,796",++++,0,4.763889,4.0,2.2,0
63854,2016-09-14,WSN,NYM,W,1,0,9.0,0.593103,1,up 9.0,2:30,D,"29,669",-,0,4.751724,4.4,2.2,0
63855,2016-09-26,WSN,ARI,L,4,14,9.0,0.587097,1,up 8.5,3:21,N,"18,707",++,0,4.735484,5.8,3.6,0
63856,2016-09-27,WSN,ARI,W,4,2,9.0,0.583333,1,up 8.5,2:40,N,"24,297",-,0,4.730769,6.6,6.2,0
63857,2016-09-28,WSN,ARI,L,0,3,6.0,0.585987,1,up 8.5,1:55,N,"20,577",+,0,4.726115,5.8,6.0,0
63858,2016-09-29,WSN,ARI,W,5,3,9.0,0.582278,1,up 7.5,2:55,D,"21,618",-,0,4.696203,4.8,5.4,0
63859,2016-09-30,WSN,MIA,L,4,7,9.0,0.584906,1,up 8.0,3:08,N,"30,857",+,0,4.698113,4.6,5.8,0
63860,2016-10-01,WSN,MIA,W,2,1,9.0,0.581250,1,up 7.0,3:03,D,"31,635",-,0,4.693750,3.4,5.8,0
63861,2016-10-02,WSN,MIA,W,10,7,9.0,0.583851,1,up 7.0,3:36,D,"28,730",+,0,4.677019,3.0,3.2,0

In [318]:
new_gb_t = []
for x in test_gb['gb']:
    if 'up' in x:
        new_gb_t.append(x.replace('up',''))
    if 'up' not in x and 'Tied' not in x:
        new_gb_t.append('-' + x )  
    if 'Tied' in x:
        new_gb_t.append('0')

In [319]:
len(new_gb_t)

63858

In [232]:
len(test_gb['gb'])

63858

In [335]:
len(new_gb_str)

63858

In [334]:
new_gb_str=[]
for x in new_gb_t:
    if x == '-0':
        new_gb_str.append(0)        
    elif '- ' in x:
        new_gb_str.append(x.replace('- ','-'))
    else:
        new_gb_str.append(x)

In [336]:
gb_float_list = []
for x in new_gb_str:
    gb_float_list.append(float(x))

In [337]:
len(gb_float_list)

63858

In [338]:
no_nan_att_data['gb']=gb_float_list

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [244]:
no_nan_att_data['date'] = pd.to_datetime(no_nan_att_data.date)
no_nan_att_data['time'] = pd.to_datetime(no_nan_att_data.time)

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [253]:
no_nan_att_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 63858 entries, 0 to 63861
Data columns (total 19 columns):
date               63858 non-null datetime64[ns]
team               63858 non-null object
opponent           63858 non-null object
w_or_l             63858 non-null object
runs               63858 non-null int64
runs_allowed       63858 non-null int64
innings            63858 non-null float64
record             63858 non-null float64
div_rank           63858 non-null int64
gb                 63858 non-null object
time               63858 non-null int64
d_or_n             63858 non-null object
attendance         63858 non-null object
streak             63858 non-null object
double_header      63858 non-null int64
runs_pg            63858 non-null float64
runs_ma            61866 non-null float64
runs_allowed_ma    63858 non-null float64
opening_day        63858 non-null int64
dtypes: datetime64[ns](1), float64(5), int64(6), object(7)
memory usage: 9.7+ MB

In [250]:
minutes_list=[]
for x in no_nan_att_data['time']:
    minutes_list.append(x.hour * 60 + x.minute)

In [252]:
no_nan_att_data['time']=minutes_list

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [255]:
year_dummy = pd.get_dummies(no_nan_att_data['date'].dt.year)

In [259]:
month_dummy = pd.get_dummies(no_nan_att_data['date'].dt.month)
month_dummy.columns = ['march','april', 'may','june','july','aug','sep','oct']

In [261]:
weekday_dummy = pd.get_dummies(no_nan_att_data['date'].dt.weekday)
weekday_dummy.columns=['M', 'T', 'W', 'TH', 'F', 'SA', 'S']

In [263]:
day_dummy = pd.get_dummies(no_nan_att_data['d_or_n'],prefix='time')

In [266]:
streak_dummy=pd.get_dummies(no_nan_att_data['streak'])

In [276]:
col_list_t = [str(s) for s in streak_dummy.columns if type(x) == int]

In [348]:
col_list_t

['0',
 '+',
 '++',
 '+++',
 '++++',
 '+++++',
 '++++++',
 '+++++++',
 '++++++++',
 '+++++++++',
 '++++++++++',
 '+++++++++++',
 '++++++++++++',
 '+++++++++++++',
 '++++++++++++++',
 '+++++++++++++++',
 '++++++++++++++++',
 '+++++++++++++++++',
 '++++++++++++++++++',
 '+++++++++++++++++++',
 '-',
 '--',
 '---',
 '----',
 '-----',
 '------',
 '-------',
 '--------',
 '---------',
 '----------',
 '-----------',
 '------------',
 '-------------',
 '--------------',
 '---------------',
 '0']

In [364]:
streak_col = []
for x in col_list_t:
    if '+' in x:
        streak_col.append('w'+str(len(x)))
    if '-' in x:
        streak_col.append('l' + str(len(x)))  
    if '0' in x:
        streak_col.append('0')

In [365]:
streak_col

['0',
 'w1',
 'w2',
 'w3',
 'w4',
 'w5',
 'w6',
 'w7',
 'w8',
 'w9',
 'w10',
 'w11',
 'w12',
 'w13',
 'w14',
 'w15',
 'w16',
 'w17',
 'w18',
 'w19',
 'l1',
 'l2',
 'l3',
 'l4',
 'l5',
 'l6',
 'l7',
 'l8',
 'l9',
 'l10',
 'l11',
 'l12',
 'l13',
 'l14',
 'l15',
 '0']

In [288]:
streak_dummy.columns[3]

'+++'

In [285]:
len(col_list_t)

36

In [366]:
streak_dummy.columns=streak_col

In [291]:
win_dummy = pd.get_dummies(no_nan_att_data['w_or_l'])

In [367]:
final_data = pd.concat([no_nan_att_data, win_dummy,year_dummy,month_dummy,weekday_dummy, day_dummy, streak_dummy],axis=1)

In [370]:
final_data.info(verbose=2)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 63858 entries, 0 to 63861
Data columns (total 102 columns):
date               datetime64[ns]
team               object
opponent           object
w_or_l             object
runs               int64
runs_allowed       int64
innings            float64
record             float64
div_rank           int64
gb                 float64
time               int64
d_or_n             object
attendance         object
streak             object
double_header      int64
runs_pg            float64
runs_ma            float64
runs_allowed_ma    float64
opening_day        int64
L                  uint8
T                  uint8
W                  uint8
1990               uint8
1991               uint8
1992               uint8
1993               uint8
1994               uint8
1995               uint8
1996               uint8
1997               uint8
1998               uint8
1999               uint8
2000               uint8
2001               uint8
2002               uint8
2003               uint8
2004               uint8
2005               uint8
2006               uint8
2007               uint8
2008               uint8
2009               uint8
2010               uint8
2011               uint8
2012               uint8
2013               uint8
2014               uint8
2015               uint8
2016               uint8
march              uint8
april              uint8
may                uint8
june               uint8
july               uint8
aug                uint8
sep                uint8
oct                uint8
M                  uint8
T                  uint8
W                  uint8
TH                 uint8
F                  uint8
SA                 uint8
S                  uint8
time_D             uint8
time_N             uint8
0                  uint8
w1                 uint8
w2                 uint8
w3                 uint8
w4                 uint8
w5                 uint8
w6                 uint8
w7                 uint8
w8                 uint8
w9                 uint8
w10                uint8
w11                uint8
w12                uint8
w13                uint8
w14                uint8
w15                uint8
w16                uint8
w17                uint8
w18                uint8
w19                uint8
l1                 uint8
l2                 uint8
l3                 uint8
l4                 uint8
l5                 uint8
l6                 uint8
l7                 uint8
l8                 uint8
l9                 uint8
l10                uint8
l11                uint8
l12                uint8
l13                uint8
l14                uint8
l15                uint8
0                  uint8
dtypes: datetime64[ns](1), float64(6), int64(6), object(6), uint8(83)
memory usage: 14.8+ MB

In [387]:
final_data.to_pickle('Capstone/Data/final_data.pkl')

In [371]:
final_data['gb']

0         0.0
1        -1.0
2        -0.5
3         0.0
4         0.0
5        -1.0
6        -2.0
7        -1.0
8        -3.0
9        -3.0
10       -4.0
11       -3.0
12       -3.0
13       -3.0
14       -6.0
15       -5.0
16       -5.0
17       -5.0
18       -4.0
19       -3.0
20       -2.0
21       -2.0
22       -2.5
23       -2.5
24       -1.0
25       -1.0
26       -1.0
27       -1.0
28       -1.5
29       -0.5
         ...
63832     7.0
63833     7.0
63834     7.0
63835     7.0
63836     6.5
63837     7.5
63838     7.5
63839     8.5
63840     8.0
63841     7.0
63842     8.0
63843     8.0
63844     8.0
63845     8.5
63846     8.5
63847     8.5
63848     8.5
63849     8.0
63850     8.0
63851     9.0
63852     9.0
63853    10.0
63854     9.0
63855     8.5
63856     8.5
63857     8.5
63858     7.5
63859     8.0
63860     7.0
63861     7.0
Name: gb, dtype: float64

In [346]:
final_data.info(verbose=2)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 63858 entries, 0 to 63861
Data columns (total 102 columns):
date               datetime64[ns]
team               object
opponent           object
w_or_l             object
runs               int64
runs_allowed       int64
innings            float64
record             float64
div_rank           int64
gb                 float64
time               int64
d_or_n             object
attendance         int64
streak             object
double_header      int64
runs_pg            float64
runs_ma            float64
runs_allowed_ma    float64
opening_day        int64
L                  uint8
T                  uint8
W                  uint8
1990               uint8
1991               uint8
1992               uint8
1993               uint8
1994               uint8
1995               uint8
1996               uint8
1997               uint8
1998               uint8
1999               uint8
2000               uint8
2001               uint8
2002               uint8
2003               uint8
2004               uint8
2005               uint8
2006               uint8
2007               uint8
2008               uint8
2009               uint8
2010               uint8
2011               uint8
2012               uint8
2013               uint8
2014               uint8
2015               uint8
2016               uint8
march              uint8
april              uint8
may                uint8
june               uint8
july               uint8
aug                uint8
sep                uint8
oct                uint8
M                  uint8
T                  uint8
W                  uint8
TH                 uint8
F                  uint8
SA                 uint8
S                  uint8
time_D             uint8
time_N             uint8
0                  uint8
w1                 uint8
w2                 uint8
w3                 uint8
w4                 uint8
w5                 uint8
w6                 uint8
w7                 uint8
w8                 uint8
w9                 uint8
w10                uint8
w11                uint8
w12                uint8
w13                uint8
w14                uint8
w15                uint8
w16                uint8
w17                uint8
w18                uint8
w19                uint8
-1                 uint8
-2                 uint8
-3                 uint8
-4                 uint8
-5                 uint8
-6                 uint8
-7                 uint8
-8                 uint8
-9                 uint8
-10                uint8
-11                uint8
-12                uint8
-13                uint8
-14                uint8
-15                uint8
0                  uint8
dtypes: datetime64[ns](1), float64(6), int64(7), object(5), uint8(83)
memory usage: 14.8+ MB

In [381]:
final_data['attendance'] =[x.replace(',', '') for x in list(final_data['attendance'].values)]

In [382]:
final_data['attendance']=final_data['attendance'].astype(int)

In [360]:
test_merge = final_data['0'].copy()

In [359]:
test_merge

       a  b
0      0  1
1      0  0
2      0  0
3      0  0
4      0  0
5      0  0
6      0  0
7      0  0
8      0  0
9      0  0
10     0  0
11     0  0
12     0  0
13     0  0
14     0  0
15     0  0
16     0  0
17     0  0
18     0  0
19     0  0
20     0  0
21     0  0
22     0  0
23     0  0
24     0  0
25     0  0
26     0  0
27     0  0
28     0  0
29     0  0
...   .. ..
63832  0  0
63833  0  0
63834  0  0
63835  0  0
63836  0  0
63837  0  0
63838  0  0
63839  0  0
63840  0  0
63841  0  0
63842  0  0
63843  0  0
63844  0  0
63845  0  0
63846  0  0
63847  0  0
63848  0  0
63849  0  0
63850  0  0
63851  0  0
63852  0  0
63853  0  0
63854  0  0
63855  0  0
63856  0  0
63857  0  0
63858  0  0
63859  0  0
63860  0  0
63861  0  0

[63858 rows x 2 columns]

In [361]:
test_merge.columns = ['a','b']

In [375]:
no_streak=test_merge['a'] + test_merge['b']

In [374]:
no_streak_df=pd.DataFrame()

In [376]:
no_streak_df['streak_0'] = no_streak

In [377]:
final_data = pd.concat([final_data,no_streak_df],axis=1)

In [384]:
final_data.drop('0',axis=1,inplace=True)

In [386]:
final_data.info(verbose=3)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 63858 entries, 0 to 63861
Data columns (total 101 columns):
date               datetime64[ns]
team               object
opponent           object
w_or_l             object
runs               int64
runs_allowed       int64
innings            float64
record             float64
div_rank           int64
gb                 float64
time               int64
d_or_n             object
attendance         int64
streak             object
double_header      int64
runs_pg            float64
runs_ma            float64
runs_allowed_ma    float64
opening_day        int64
L                  uint8
T                  uint8
W                  uint8
1990               uint8
1991               uint8
1992               uint8
1993               uint8
1994               uint8
1995               uint8
1996               uint8
1997               uint8
1998               uint8
1999               uint8
2000               uint8
2001               uint8
2002               uint8
2003               uint8
2004               uint8
2005               uint8
2006               uint8
2007               uint8
2008               uint8
2009               uint8
2010               uint8
2011               uint8
2012               uint8
2013               uint8
2014               uint8
2015               uint8
2016               uint8
march              uint8
april              uint8
may                uint8
june               uint8
july               uint8
aug                uint8
sep                uint8
oct                uint8
M                  uint8
T                  uint8
W                  uint8
TH                 uint8
F                  uint8
SA                 uint8
S                  uint8
time_D             uint8
time_N             uint8
w1                 uint8
w2                 uint8
w3                 uint8
w4                 uint8
w5                 uint8
w6                 uint8
w7                 uint8
w8                 uint8
w9                 uint8
w10                uint8
w11                uint8
w12                uint8
w13                uint8
w14                uint8
w15                uint8
w16                uint8
w17                uint8
w18                uint8
w19                uint8
l1                 uint8
l2                 uint8
l3                 uint8
l4                 uint8
l5                 uint8
l6                 uint8
l7                 uint8
l8                 uint8
l9                 uint8
l10                uint8
l11                uint8
l12                uint8
l13                uint8
l14                uint8
l15                uint8
streak_0           uint8
dtypes: datetime64[ns](1), float64(6), int64(7), object(5), uint8(82)
memory usage: 14.7+ MB

In [388]:
final_drop = final_data.drop(['w_or_l','d_or_n', 'streak'],axis=1)

In [389]:
final_drop.info(verbose=1)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 63858 entries, 0 to 63861
Data columns (total 98 columns):
date               63858 non-null datetime64[ns]
team               63858 non-null object
opponent           63858 non-null object
runs               63858 non-null int64
runs_allowed       63858 non-null int64
innings            63858 non-null float64
record             63858 non-null float64
div_rank           63858 non-null int64
gb                 63858 non-null float64
time               63858 non-null int64
attendance         63858 non-null int64
double_header      63858 non-null int64
runs_pg            63858 non-null float64
runs_ma            61866 non-null float64
runs_allowed_ma    63858 non-null float64
opening_day        63858 non-null int64
L                  63858 non-null uint8
T                  63858 non-null uint8
W                  63858 non-null uint8
1990               63858 non-null uint8
1991               63858 non-null uint8
1992               63858 non-null uint8
1993               63858 non-null uint8
1994               63858 non-null uint8
1995               63858 non-null uint8
1996               63858 non-null uint8
1997               63858 non-null uint8
1998               63858 non-null uint8
1999               63858 non-null uint8
2000               63858 non-null uint8
2001               63858 non-null uint8
2002               63858 non-null uint8
2003               63858 non-null uint8
2004               63858 non-null uint8
2005               63858 non-null uint8
2006               63858 non-null uint8
2007               63858 non-null uint8
2008               63858 non-null uint8
2009               63858 non-null uint8
2010               63858 non-null uint8
2011               63858 non-null uint8
2012               63858 non-null uint8
2013               63858 non-null uint8
2014               63858 non-null uint8
2015               63858 non-null uint8
2016               63858 non-null uint8
march              63858 non-null uint8
april              63858 non-null uint8
may                63858 non-null uint8
june               63858 non-null uint8
july               63858 non-null uint8
aug                63858 non-null uint8
sep                63858 non-null uint8
oct                63858 non-null uint8
M                  63858 non-null uint8
T                  63858 non-null uint8
W                  63858 non-null uint8
TH                 63858 non-null uint8
F                  63858 non-null uint8
SA                 63858 non-null uint8
S                  63858 non-null uint8
time_D             63858 non-null uint8
time_N             63858 non-null uint8
w1                 63858 non-null uint8
w2                 63858 non-null uint8
w3                 63858 non-null uint8
w4                 63858 non-null uint8
w5                 63858 non-null uint8
w6                 63858 non-null uint8
w7                 63858 non-null uint8
w8                 63858 non-null uint8
w9                 63858 non-null uint8
w10                63858 non-null uint8
w11                63858 non-null uint8
w12                63858 non-null uint8
w13                63858 non-null uint8
w14                63858 non-null uint8
w15                63858 non-null uint8
w16                63858 non-null uint8
w17                63858 non-null uint8
w18                63858 non-null uint8
w19                63858 non-null uint8
l1                 63858 non-null uint8
l2                 63858 non-null uint8
l3                 63858 non-null uint8
l4                 63858 non-null uint8
l5                 63858 non-null uint8
l6                 63858 non-null uint8
l7                 63858 non-null uint8
l8                 63858 non-null uint8
l9                 63858 non-null uint8
l10                63858 non-null uint8
l11                63858 non-null uint8
l12                63858 non-null uint8
l13                63858 non-null uint8
l14                63858 non-null uint8
l15                63858 non-null uint8
streak_0           63858 non-null uint8
dtypes: datetime64[ns](1), float64(6), int64(7), object(2), uint8(82)
memory usage: 13.3+ MB

In [393]:
final_drop.to_pickle('Capstone/Data/final_drop.pkl')